#SPDX-License-Identifier: MIT-0
---
- name: Install Docker
  shell: >
    apt update &&
    apt install -y docker.io &&
    systemctl enable docker &&
    systemctl start docker
  
- name: Run SonarQube in Docker
  command: docker run -d -p 9000:9000 --name sonarqube sonarqube
