- name: SSH keyscan all inventory hosts
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    known_hosts_file: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
  
  tasks:
    - name: Get all hosts from inventory
      set_fact:
        all_inventory_hosts: "{{ groups['containers'] }}"
    
    - name: Get IP addresses for all hosts
      set_fact:
        host_ips: "{{ host_ips | default({}) | combine({item: hostvars[item]['ansible_host'] | default(item)}) }}"
      loop: "{{ all_inventory_hosts }}"
    
    - name: Scan SSH keys for all hosts (using IPs)
      known_hosts:
        path: "{{ known_hosts_file }}"
        name: "{{ host_ips[item] }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + host_ips[item]) }}"
        state: present
      loop: "{{ all_inventory_hosts }}"
      register: keyscan_results
      ignore_errors: yes
    
    - name: Show results
      debug:
        msg: "SSH key scanning completed for {{ all_inventory_hosts | length }} hosts"
    