#SPDX-License-Identifier: MIT-0
---
- name: Check if port mapping already exists
  shell: lxc config device list {{ item.node_name }} | grep "{{ item.node_name }}{{ item.port }}" || true
  register: existing_device
  with_items: "{{ map }}"

# - name: Result
#   debug:
#     var: existing_device

- name: Remove existing port mapping if it exists
  ansible.builtin.command: lxc config device remove {{ item.item.node_name }} {{ item.item.node_name }}{{ item.item.port }}
  delegate_to: localhost
  loop: "{{ existing_device.results }}"
  when: item.stdout != ""

- name: Add port mapping to container
  command: >
    lxc config device add {{ item.node_name }} {{ item.node_name }}{{ item.port }} proxy 
    listen={{ item.protocol }}:0.0.0.0:{{ item.port }}
    connect={{ item.protocol }}:127.0.0.1:{{ item.port }}
  delegate_to: localhost
  with_items: "{{ map }}"