#SPDX-License-Identifier: MIT-0
---
- name: Check if port mapping already exists
  shell: lxc config device list {{ item.node_name }} | grep "{{ item.node_name }}{{ item.port }}" || true
  register: existing_device
  with_items: "{{ map }}"

- name: Remove existing port mapping if it exists
  command: lxc config device remove {{ item.node_name }} {{ item.node_name }}{{ item.port }}
  delegate_to: localhost
  when: existing_device.stdout != ""
  with_items: "{{ map }}"

- name: Add port mapping to container
  command: >
    lxc config device add {{ item.node_name }} {{ item.node_name }}{{ item.port }} proxy 
    listen={{ protocol }}:0.0.0.0:{{ item.port }}
    connect={{ protocol }}:127.0.0.1:{{ item.port }}
  delegate_to: localhost
  with_items: "{{ map }}"