#SPDX-License-Identifier: MIT-0
---

- name: Iptables flush nat
  iptables:
    table: nat
    chain: '{{ item }}'
    flush: yes
  with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]

- name: Enable port forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  delegate_to: localhost

- name: Prerouting
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: '{{ item.port }}'
    jump: DNAT
    to_destination: '{{ item.ip }}:{{ item.port }}'
    state: present
  with_items: "{{ map }}"

- name: Allow Forwarding In
  iptables:
    chain: FORWARD
    protocol: tcp
    # in_interface: "{{ ansible_default_ipv4.interface }}"
    # out_interface: lxcbr0
    destination_port: '{{ item.port }}'
    jump: ACCEPT
    state: present
  with_items: "{{ map }}"

# - name: Allow Forwarding Out
#   iptables:
#     chain: FORWARD
#     protocol: tcp
#     in_interface: lxcbr0
#     out_interface: "{{ ansible_default_ipv4.interface }}"
#     destination_port: '{{ item.port }}'
#     jump: ACCEPT
#     state: present
#   with_items: "{{map}}"
    
- name: POSTROUTING
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: '{{ ansible_default_ipv4.interface }}'
    jump: MASQUERADE
    state: present

