#SPDX-License-Identifier: MIT-0
---

map:
  - ip: "{{ hostvars['nginx']['ansible_host'] }}"
    port: 80
  - ip: "{{ hostvars['prometheus']['ansible_host'] }}"
    port: 9090
  - ip: "{{ hostvars['grafana']['ansible_host'] }}"
    port: 3000
  - ip: "{{ hostvars['jenkins']['ansible_host'] }}"
    port: 8080
  - ip: "{{ hostvars['sonarqube']['ansible_host'] }}"
    port: 9000

